# Generated by Django 4.2.4 on 2023-09-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_candidato_delete_bancoespera'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='diretoria_desejada',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
