# Generated by Django 4.2.4 on 2023-09-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_candidato_diretoria_desejada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='idVendedor',
        ),
        migrations.AddField(
            model_name='usuario',
            name='diretoria',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
