# Generated by Django 4.2.4 on 2023-09-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_venda_idvendedor_usuario_diretoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
