# Generated by Django 4.2.4 on 2023-09-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_eventos_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='hora',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
